# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='resume',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
