# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20181004_1304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Resume',
        ),
    ]
