# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_resume_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
